### PR TITLE
feat: experience section

### PR DESCRIPTION
**Pull request by FlorianVDP**

### CODE REVIEW

**Comment by FlorianVDP** [comment]
Disabled Portfolio section, because we don't have datas.

image

**Comment by ValMgr** [comment]
Why would we disable portfolio ? It's not a probleme to display fake data. We showd this feature to UX yesterday and they can still work around it.

**Comment by ValMgr** [comment]
And why there is an empty file `Profile2.svelte` ?

**Comment by iOiurson** [comment]
We can leave the portfolio hidden, and open an issue to fill it with static images until we deal with it properly.

But the empty `Profile2.svelte` should indeed be removed from this PR.

**Comment by ValMgr** [comment]
Yes but portfolio is already filled with static images, and i'm not really confortable to remove a "feature" we showd and explained to UX. They planned to work around the toggles button . 

We can discuss about the usfulness of the feature together next friday but I think it would be better to merge the experience feature alone and open an discussion about portfolio aside.

**Comment by iOiurson** [comment]
Please confirm that the files related to supabase config are expected in this PR.

If not, please remove them.

If yes, ok we can merge this, but it should have been a different PR.

**Comment by ValMgr** [comment]
Done

**Review by iOiurson — APPROVED** [review]

**Pull request merged**
